name: Build Rust App

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build in release mode
      run: cargo build --release

    - name: Upload binary (Linux)
      uses: actions/upload-artifact@v3
      with:
        name: my-binary
        path: target/release/<your_binary_name>
