name: Build and Release Python App

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller --onefile main.py

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
